// *** DO NOT EDIT THIS FILE FOR A COMP30070 ASSIGNMENT ****

val scala3Version = "3.2.0"

lazy val root = project
  .in(file("."))
  .settings(
    name := "cards",
    version := "0.1.0-SNAPSHOT",

    scalaVersion := scala3Version,

    libraryDependencies += "org.scalatest" %% "scalatest-funsuite" % "3.2.14" % "test"
  )